### ISSUE TITLE
Guidance on Envoy 0.17.0 with protocol V3?

### ISSUE THREAD

**Issue by caboteria** [3scale-ops/marin3r#74]
Hi! Marin3r works great for us up to Envoy 0.16.2 but we'd like to update to Envoy 0.17.0 which has stronger deprecation of protocol V2. This impacts Marin3r in many ways, I'm sure, and I see that some work has been done already, but I wonder if anyone has any guidance on how to upgrade?

I tried the kuard sidecar demo in the Marin3r README and it works with 0.16.2 but with envoy 0.17.0 crashes and logs these messages:
```
[2021-02-18 23:20:51.418][1][warning][misc] [source/common/protobuf/message_validator_impl.cc:21] Deprecated field: type envoy.config.core.v3.ConfigSource Using the default now-deprecated value AUTO for enum 'envoy.config.core.v3.ConfigSo
urce.resource_api_version' from file config_source.proto. This enum value will be removed from Envoy soon so a non-default value must now be explicitly set. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_hi
story for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and h
ighly discouraged override.
[2021-02-18 23:20:51.419][1][critical][main] [source/server/server.cc:109] error initializing configuration '/etc/envoy/bootstrap/config.json': Proto constraint validation failed (UpstreamTlsContextValidationError.CommonTlsContext: ["embe
dded message failed validation"] | caused by CommonTlsContextValidationError.TlsCertificateSdsSecretConfigs[i]: ["embedded message failed validation"] | caused by SdsSecretConfigValidationError.Name: ["value length must be at least " '\x0
1' " runes"]): common_tls_context {
  tls_certificate_sds_secret_configs {
    sds_config {
      path: "/etc/envoy/bootstrap/tls_certificate_sds_secret.json"
    }
  }
}

[2021-02-18 23:20:51.419][1][info][main] [source/server/server.cc:782] exiting
Proto constraint validation failed (UpstreamTlsContextValidationError.CommonTlsContext: ["embedded message failed validation"] | caused by CommonTlsContextValidationError.TlsCertificateSdsSecretConfigs[i]: ["embedded message failed valida
tion"] | caused by SdsSecretConfigValidationError.Name: ["value length must be at least " '\x01' " runes"]): common_tls_context {
  tls_certificate_sds_secret_configs {
    sds_config {
      path: "/etc/envoy/bootstrap/tls_certificate_sds_secret.json"
    }
  }
}
```

I tried adding the following annotations to the kuard deployment yaml, but with no success:
```
        marin3r.3scale.net/envoy-image: envoyproxy/envoy:v1.17.0
        marin3r.3scale.net/envoy-api-version: v3
        marin3r.3scale.net/ads-configmap: envoy-sidecar-bootstrap-v3
        marin3r.3scale.net/config-volume: envoy-sidecar-bootstrap-v3

```
The Envoy sidecar container is mounting the envoy-sidecar-bootstrap-v3 properly, but evidently Envoy doesn't like what's in there.

Does anyone have any guidance on using Marin3r with Envoy 0.17.0?

Thank you!

**Comment by acnodal-tc** [comment]
Looking into the error and this page https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/auth/secret.proto#envoy-api-msg-auth-sdssecretconfig , they seem to indicate that there should be a "name" key/value in the object with "sds_config", e.g.,

```
              "tls_certificate_sds_secret_configs": [
                {
                  "name": "note-sure-what-this-refers-to",
                  "sds_config": {
                    "path": "/etc/envoy/bootstrap/tls_certificate_sds_secret.json"
                  }
                }
              ]

```

**Comment by roivaz** [comment]
Hi! There are several things to consider when upgrading the envoy version, even when using the same api version:

* Minor changes within an envoy API version: even if the API version you are using for both 1.16.2 and 1.17 is V3, envoy introduces minor changes between releases without changing the API version number. This changes are usually described in the release notes: https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.17.0. They are usually minor changes like deprecating a field in favor of a different one or slightly modifying some syntax. I think this is the case in the error you are getting, you might need to modify your config slightly to make it work with 1.17.
* Marin3r depends on https://github.com/envoyproxy/go-control-plane, which is a base implementation of an xDS server. This project provides all the protobuf proto definitions for the envoy API. Marin3r v0.7.0  uses go-control-plane v0.9.7, which in turn has proto definitions from commit 241358e0ac7716fac24ae6c19c7dcea67357e70e in https://github.com/envoyproxy/envoy, which is from last October. This all means that while 1.17 is expected to work with Marin3r 0.7.0 in a majority of cases, support is not 100% ensured because changes to the API could have happened between October (api definitions that Marin3r v0.7.0 has) and the release of 1.17. It is unlikely that you are hitting this problem but is something to consider.

**Comment by acnodal-tc** [comment]
Thank you for the insight! It looks like your first point (Envoy inter-version API changes) is what I'm running into. I was able to get 0.17.0 bootstrap working last night with canned bootstrap envoy.config and SDS tls_certificate_sds_secret responses. The fix is to add a "name" key/value to *both* files so Envoy can link the two. Evidently versions of Envoy up to 0.16.2 didn't require that. I see that you've already implemented a V3 bootstrap config next to the V2 one so that should be an easy fix. Not sure about the SDS response file, though.

Thank you!

**Comment by roivaz** [comment]
This is the code that generates the SDS response file

https://github.com/3scale/marin3r/blob/df8ac5240d37e25dd5d5a9005564d100ae0de98c/pkg/envoy/bootstrap/v3/bootstrap.go#L171-L194

Which in turn uses the `NewSecretFromPath` to generate the appropriate versioned SDS resource, which in the case of the V3 API is:

https://github.com/3scale/marin3r/blob/df8ac5240d37e25dd5d5a9005564d100ae0de98c/pkg/envoy/resources/v3/resources.go#L66-L83

In fact is see that I already set a parameter `name` in there, but the function is not using it at all. I guess I probably forgot to add the `Name` field to the `Secret` resource and never realised it as it works without it for <1.17 :sweat_smile:
